# Generated by Django 6.0.3 on 2026-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SAVING', 'Saving')], max_length=10),
        ),
    ]
